spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sohrabq
    username: sohrabq
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081